"""API cards: compact, exact references for Python modules, generated by introspecting the sandbox's own Python.

Nothing is hand-written: a card lists what really exists in the runtime the model's code will run in (public
functions and classes with signatures, class methods, constants) plus each item's first docstring line.
Cards are cached on disk per module. Unknown or non-importable modules simply get no card.
"""
import json
import os
import re

import sandbox_path  # noqa: F401  (puts tooling/wasi-python on sys.path)
import sandbox

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "apicards-cache.json")
MAX_CARD_CHARS = 3200

_INTROSPECT = r'''
import importlib, inspect, json, sys
name = sys.argv[1]
try:
    m = importlib.import_module(name)
except Exception as e:
    print(json.dumps({"error": repr(e)})); sys.exit(0)

def first(doc):
    doc = (doc or "").strip().splitlines()
    return doc[0].strip()[:120] if doc else ""

def sig(obj):
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(...)"

out = {"module": name, "doc": first(m.__doc__), "functions": [], "classes": [], "exceptions": [], "constants": []}
public = sorted(set((getattr(m, "__all__", None) or []) + [n for n in dir(m) if not n.startswith("_")]))
for n in public:
    try:
        o = getattr(m, n)
    except AttributeError:
        continue
    if inspect.ismodule(o) or getattr(o, "__module__", name) not in (name, None, "builtins") and not (n.isupper()):
        if not (inspect.isclass(o) or callable(o)) and n.isupper():
            pass
        elif inspect.isclass(o) or callable(o):
            continue
    if inspect.isclass(o) and issubclass(o, BaseException):
        out["exceptions"].append(n)
    elif inspect.isclass(o):
        fields = []
        sl = getattr(o, "__slots__", None)
        if isinstance(sl, dict):
            fields = [k for k in sl if not k.startswith("_")]
        elif isinstance(sl, (list, tuple)):
            fields = [k for k in sl if not k.startswith("_")]
        meths = []
        for mn, mo in sorted(vars(o).items()):
            if mn.startswith("_"):
                continue
            if isinstance(mo, property):
                fields.append(mn)
            elif callable(mo) or isinstance(mo, (classmethod, staticmethod)):
                f = mo.__func__ if isinstance(mo, (classmethod, staticmethod)) else mo
                meths.append([mn, sig(f)])
        out["classes"].append([n, sig(o), first(o.__doc__), sorted(set(fields)), meths])
    elif callable(o):
        out["functions"].append([n, sig(o), first(o.__doc__)])
    elif isinstance(o, (int, str, bytes, float)) and n.isupper():
        out["constants"].append([n, repr(o)[:24]])
print(json.dumps(out))
'''


def _load_cache():
    try:
        return json.load(open(CACHE, encoding="utf-8"))
    except (OSError, ValueError):
        return {}


_cache = _load_cache()


def introspect(module):
    if module in _cache:
        return _cache[module]
    r = sandbox.run({"intro.py": _INTROSPECT}, ["/work/intro.py", module], timeout=20, mem_mb=256)
    try:
        data = json.loads(r["stdout"].decode("utf-8"))
    except (ValueError, UnicodeDecodeError):
        data = {"error": "introspection failed"}
    _cache[module] = data
    try:
        json.dump(_cache, open(CACHE, "w", encoding="utf-8"))
    except OSError:
        pass
    return data


def card(module, focus=()):
    """Render a card. Constants first (complete), then functions, classes with fields; full method signatures only
    for classes whose name appears in the request; exceptions on one line."""
    d = introspect(module)
    if "error" in d:
        return ""
    focus = {f.lower() for f in focus}
    hit = lambda n: n.lower() in focus
    lines = [f"## {module} (exact API of this Python 3.12 runtime): {d['doc']}"]
    if d["constants"]:
        lines.append("constants: " + ", ".join(f"{n}={v}" for n, v in d["constants"]))
    for n, s_, doc in sorted(d["functions"], key=lambda x: (not hit(x[0]), x[0])):
        lines.append(f"- {module}.{n}{s_}" + (f"  # {doc}" if doc and hit(n) else ""))
    for n, s_, doc, fields, meths in sorted(d["classes"], key=lambda x: (not hit(x[0]), x[0])):
        lines.append(f"- class {module}.{n}{s_}" + (f"  # {doc}" if doc else ""))
        if fields:
            lines.append(f"    fields: {', '.join(fields)}")
        if meths:
            if hit(n):
                lines.extend(f"    .{mn}{ms}" for mn, ms in meths)
            else:
                lines.append("    methods: " + ", ".join(mn for mn, _ in meths))
    if d["exceptions"]:
        lines.append("exceptions: " + ", ".join(d["exceptions"]))
    text = chr(10).join(lines)
    if len(text) > MAX_CARD_CHARS:
        text = text[:MAX_CARD_CHARS].rsplit(chr(10), 1)[0] + chr(10) + f"- ... (more names exist in {module})"
    return text


# words in a request that point at a stdlib module (imports are detected separately)
KEYWORDS = {
    "tarfile": r"\btar\b|\btarball\b|\bustar\b|\btarfile\b",
    "gzip": r"\bgzip\b|\.gz\b",
    "zlib": r"\bzlib\b|\bdeflate\b|\bcrc32\b",
    "zipfile": r"\bzip (file|archive)\b|\bzipfile\b",
    "base64": r"\bbase64\b|\bb64\b",
    "hashlib": r"\bsha-?256\b|\bsha-?1\b|\bmd5\b|\bhashlib\b|\bdigest\b",
    "csv": r"\bcsv\b",
    "json": r"\bjson\b",
    "sqlite3": r"\bsqlite\b",
    "datetime": r"\bdatetime\b|\btimestamp\b|\biso ?8601\b",
    "decimal": r"\bdecimal\b",
    "struct": r"\bstruct\b|\bbinary header\b",
    "re": r"\bregex\b|\bregular expression\b",
    "unicodedata": r"\bunicodedata\b|\bnormali[sz]ation form\b|\bnf[ck]d?\b",
}
IMPORT_RE = re.compile(r"^\s*(?:from\s+([A-Za-z_][\w]*)[\w.]*\s+import|import\s+([A-Za-z_][\w]*))", re.M)
CODING_TOOL_RE = re.compile(r"write|edit|run|exec|python|code|patch|file|shell|bash", re.I)


def detect_modules(text, coding):
    found = []
    for m in IMPORT_RE.finditer(text):
        name = m.group(1) or m.group(2)
        if name not in found:
            found.append(name)
    if coding:
        for mod, pat in KEYWORDS.items():
            if mod not in found and re.search(pat, text, re.I):
                found.append(mod)
    return found


def cards_for_request(body, max_modules=4):
    """Return the reference text to inject for a chat request, or "" if it is not a coding request."""
    msgs = body.get("messages") or []
    text = "\n".join(m.get("content") if isinstance(m.get("content"), str) else json.dumps(m.get("content") or "")
                     for m in msgs)
    for m in msgs:
        for c in m.get("tool_calls") or []:
            text += "\n" + str(c.get("function", {}).get("arguments", ""))
    tools = body.get("tools") or []
    # a coding request: a coding tool is offered, or the text has Python code (a python fence or an import line).
    # A bare fence is not enough: JSON examples in a non-coding task triggered cards and hurt (P1d batch).
    coding = (any(CODING_TOOL_RE.search(t.get("function", {}).get("name", "")) for t in tools)
              or ("```python" in text) or ("```py" + chr(10)) in text or bool(IMPORT_RE.search(text)))
    if not coding:
        return ""
    mods = detect_modules(text, coding)
    words = set(re.findall(r"[A-Za-z_]\w+", text))
    out = []
    for mod in mods:
        c = card(mod, focus=words)
        if c:
            out.append(c)
        if len(out) >= max_modules:
            break
    if not out:
        return ""
    return ("Reference: exact APIs of the Python modules this task involves, generated from the runtime the code "
            "will run in. Names not listed here do not exist in that module.\n\n" + "\n\n".join(out))
